version: '2'
services:
    school-app:
        image: school
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://school-mysql:3306/school?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://school-elasticsearch:9200
        ports:
            - 8080:8080
    school-mysql:
        extends:
            file: mysql.yml
            service: school-mysql
    school-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: school-elasticsearch
